import "@/styles/global.css";
import ClientLayout from "@/components/client/clientLayout";

export const metadata = {
  title: "Apotek Warehouse & POS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
