import "@/styles/global.css";
import "@ant-design/v5-patch-for-react-19";

export const metadata = {
  title: "Apotek Warehouse & POS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
